version: "3.8"
services:
   app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/e-coleta-web
      - /e-coleta-web/node_modules
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    tty: true
